# Generated by Django 5.1.4 on 2024-12-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_delete_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
