# Generated by Django 5.1.4 on 2024-12-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
