# Generated by Django 5.1.3 on 2024-12-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
