# Generated by Django 5.1.3 on 2024-12-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_brand_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_suspension',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
