# Generated by Django 5.1.3 on 2024-12-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_type_suspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='build',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
