# Generated by Django 5.1.4 on 2024-12-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_of_registration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
