# Generated by Django 5.1.4 on 2024-12-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_time_of_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='time_of_registration',
        ),
    ]
