# Generated by Django 5.1.4 on 2024-12-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='used_promo',
            field=models.BooleanField(default=False),
        ),
    ]
